### ISSUE TITLE
Criar página da aplicação

### ISSUE THREAD

**Issue by liverday** [medeirotech/devodeployar#5]
A aplicação terá uma única página, a idéia é fazer parecida com a página do [should i deploy today](https://shouldideploy.today), mas com um toque diferente.

Deixo aberto a discussão nessa issue sobre qual vai ser o design da página.

**Comment by luizhf42** [comment]
Criei um esboço bem básico do design da página no Figma: [https://www.figma.com/file/byiWhQYWIELpO82InbmAal/DevoDeployar?node-id=0%3A1&t=xinCl50xzY8rLvFL-1](https://www.figma.com/file/byiWhQYWIELpO82InbmAal/DevoDeployar?node-id=0%3A1&t=xinCl50xzY8rLvFL-1)

Fiquem a vontade para fazer sugestões.
